include_guard()

set(GCF_TEST_RESOURCE_FOLDER ${CMAKE_BINARY_DIR}/test-assets)
set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS "${GCF_TEST_RESOURCE_FOLDER}/image-mipmaps.gcf")
set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS_UNPADDED "${GCF_TEST_RESOURCE_FOLDER}/image-mipmaps-unpadded.gcf")
set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_ZLIB "${GCF_TEST_RESOURCE_FOLDER}/image-compressed-zlib.gcf")
set(GCF_TEST_RESOURCE_IMAGE_UNCOMPRESSED "${GCF_TEST_RESOURCE_FOLDER}/image-uncompressed.gcf")
set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_TEST "${GCF_TEST_RESOURCE_FOLDER}/image-compressed-test.gcf")
