include_guard()

set(GCF_TEST_RESOURCE_FOLDER ${CMAKE_BINARY_DIR}/test-assets)
set(GCF_TEST_RESOURCE_DEF_FOLDER ${CMAKE_SOURCE_DIR}/assets)

set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS "${GCF_TEST_RESOURCE_FOLDER}/image-mipmaps.gcf")
set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/image-mipmaps.json")

set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS_UNPADDED "${GCF_TEST_RESOURCE_FOLDER}/image-mipmaps-unpadded.gcf")
set(GCF_TEST_RESOURCE_IMAGE_MIPMAPS_UNPADDED_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/image-mipmaps-unpadded.json")

set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_ZLIB "${GCF_TEST_RESOURCE_FOLDER}/image-compressed-zlib.gcf")
set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_ZLIB_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/image-compressed-zlib.json")

set(GCF_TEST_RESOURCE_IMAGE_UNCOMPRESSED "${GCF_TEST_RESOURCE_FOLDER}/image-uncompressed.gcf")
set(GCF_TEST_RESOURCE_IMAGE_UNCOMPRESSED_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/image-uncompressed.json")

set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_TEST "${GCF_TEST_RESOURCE_FOLDER}/image-compressed-test.gcf")
set(GCF_TEST_RESOURCE_IMAGE_COMPRESSED_TEST_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/image-compressed-test.json")
