include_guard()

set(GCF_TEST_RESOURCE_FOLDER ${CMAKE_CURRENT_BINARY_DIR}/test-assets)
set(GCF_TEST_RESOURCE_DEF_FOLDER ${CMAKE_SOURCE_DIR}/assets)

set(GCF_TEST_RESOURCE_TEXTURE_MIPMAPS "${GCF_TEST_RESOURCE_FOLDER}/texture-mipmaps.gcf")
set(GCF_TEST_RESOURCE_TEXTURE_MIPMAPS_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/texture-mipmaps.json")

set(GCF_TEST_RESOURCE_TEXTURE_MIPMAPS_UNPADDED "${GCF_TEST_RESOURCE_FOLDER}/texture-mipmaps-unpadded.gcf")
set(GCF_TEST_RESOURCE_TEXTURE_MIPMAPS_UNPADDED_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/texture-mipmaps-unpadded.json")

set(GCF_TEST_RESOURCE_TEXTURE_COMPRESSED_ZLIB "${GCF_TEST_RESOURCE_FOLDER}/texture-compressed-zlib.gcf")
set(GCF_TEST_RESOURCE_TEXTURE_COMPRESSED_ZLIB_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/texture-compressed-zlib.json")

set(GCF_TEST_RESOURCE_TEXTURE_UNCOMPRESSED "${GCF_TEST_RESOURCE_FOLDER}/texture-uncompressed.gcf")
set(GCF_TEST_RESOURCE_TEXTURE_UNCOMPRESSED_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/texture-uncompressed.json")

set(GCF_TEST_RESOURCE_TEXTURE_COMPRESSED_TEST "${GCF_TEST_RESOURCE_FOLDER}/texture-compressed-test.gcf")
set(GCF_TEST_RESOURCE_TEXTURE_COMPRESSED_TEST_DEF "${GCF_TEST_RESOURCE_DEF_FOLDER}/texture-compressed-test.json")
